version: "3"
services:
  wolfbot:
    build: .
    image: wolfbot-docker/latest
    restart: always
    ports:
      - "8331:8331"
      - "8332:8332"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/data/db:/data/db
